USE [XWS]
GO

INSERT INTO [dbo].[FIRMA] ([NAZIV],[ADRESA],[PIB]) VALUES ('firmaA','adresaA','111111')
INSERT INTO [dbo].[FIRMA] ([NAZIV],[ADRESA],[PIB]) VALUES ('firmaB','adresaB','222222')
GO

GO

INSERT INTO [dbo].[BANKA]([NAZIV],[SWIFT],[RACUN])VALUES ('bankaA','AAAA','1111-8888')
INSERT INTO [dbo].[BANKA]([NAZIV],[SWIFT],[RACUN])VALUES ('bankaB','BBBB','1111-9999')
GO

GO

INSERT INTO [dbo].[RACUN] ([ID_BANKA],[ID_FIRMA],[RACUN],[STANJE])VALUES(1,1,'123-456', 500000)
INSERT INTO [dbo].[RACUN] ([ID_BANKA],[ID_FIRMA],[RACUN],[STANJE])VALUES(2,2,'456-123', 1500)
GO

